export const CONFIG = {
  BATCH_SIZE: 10,
  BLOCKED_RESOURCE_TYPES: new Set(["image", "media", "font", "stylesheet"]),
  BLOCKED_DOMAINS: [
    "doubleclick.net",
    "googlesyndication.com",
    "adservice.google.com",
    "adservice.google.*",
    "google-analytics.com",
    "analytics.google.com",
    "facebook.com",
    "facebook.net",
    "ads-twitter.com",
    "adroll.com",
    "taboola.com",
    "outbrain.com",
    "criteo.com",
    "scorecardresearch.com",
    "zedo.com",
    "quantserve.com",
    "moatads.com",
    "bing.com",
  ],
  USER_AGENT:
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  VIEWPORT: { width: 1920, height: 1080 },
  CROATIAN_LOWERCASE_WORDS: [
    "i",
    "u",
    "na",
    "kod",
    "do",
    "od",
    "za",
    "iz",
    "s",
    "sa",
    "k",
    "ka",
  ],
  DIRECTIONAL_WORDS: [
    "sjever",
    "jug",
    "istok",
    "zapad",
    "sjeverni",
    "južni",
    "istočni",
    "zapadni",
  ],
};
